version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "main"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "beta"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "next"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
