version: '3.8'

services:
  srtla-server:
    image: alexanderwagnerdev/srtla-server:latest
    container_name: srtla-server
    restart: unless-stopped
    ports:
      - "8789:8080/tcp"
      - "5000:5000/udp"
      - "4001:4001/udp"
      - "4000:4000/udp"
    volumes:
      - ./data:/var/lib/sls

  slspanel:
    image: alexanderwagnerdev/slspanel:latest
    container_name: slspanel
    restart: unless-stopped
    environment:
      - LANG=en
      - TZ=UTC
      - SLS_API_URL=http://localhost:8789
      - SLS_API_KEY=yourapikey
      - SRT_PUBLISH_PORT=4000
      - SRT_PLAYER_PORT=4001
      - SRTLA_PUBLISH_PORT=5000
      - SLS_DOMAIN_IP=localhost
      - SLS_STATS_PORT=8789
      - REQUIRE_LOGIN=True
      - USERNAME=admin
      - PASSWORD=password
    ports:
      - "8000:8000/tcp"
